services:
  - type: web
    name: drf-api-service
    env: python
    buildCommand: ""
    startCommand: gunicorn DRF_Project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Django_Rest_Main.settings
      - key: RENDER
        value: true
    autoDeploy: true
